version: '3'

services:
  db:
    image: postgres:16-alpine3.19
    restart: always

    environment:
      POSTGRES_DB: task_manager
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5